get products by ownerId
nss-evening-cohort-9/StudentLoansBangazon.API pull request #17
Opened 2019-12-04 01:43 UTC by matthewaustinbell

2019-12-07 16:28 UTC, HeathJHMoore requested changes

2019-12-07 16:28 UTC, HeathJHMoore commented on StudentLoans/DataAccess/ProductRepository.cs
> +                var sql = @"select OwnerId, [Name], IsRented from Products
This looks good but the only other thing we need to do is add the rest of the product fields to the SQL Select statement
We could probably just get away with changing the query to this
```
SELECT p.*
 FROM Products p
 WHERE OwnerId = @OwnerId AND isRented = 0;
```

2019-12-07 17:12 UTC, matthewaustinbell commented on StudentLoans/DataAccess/ProductRepository.cs
> +                var sql = @"select OwnerId, [Name], IsRented from Products
ok thanks i pushed that up if you would like to test it on your end

2019-12-10 02:10 UTC, HeathJHMoore commented
👍

2019-12-10 02:20 UTC, HeathJHMoore commented
👍

2019-12-10 02:20 UTC, merged